[package]
name = "chat"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.13.1", features = ["unstable"] }
serde = { version = "1.0.219", features = ["derive", "rc"] }
serde_json = "1.0.140"
tokio = { version = "1.45.0", features = ["sync"] }
